{
  "final_name": "L_Bracket",
  "units": "mm",
  "coordinate_system": {
    "Origin": [0, 0, 0],
    "X Axis": [1, 0, 0],
    "Y Axis": [0, 1, 0]
  },
  "parts": {
    "Body1": {
      "profiles": {
        "Profile1": {
          "sketch_plane": {
            "origin": [0, 0, 0],
            "x_dir": [1, 0, 0],
            "y_dir": [0, 1, 0]
          },
          "profile_id": "l_shape",
          "loops": [
            {
              "loop_id": "base",
              "curves": [
                {
                  "curve_id": "line_1",
                  "type": "line",
                  "start_point": [0, 0],
                  "end_point": [80, 0]
                },
                {
                  "curve_id": "line_2",
                  "type": "line",
                  "start_point": [80, 0],
                  "end_point": [80, 20]
                },
                {
                  "curve_id": "line_3",
                  "type": "line",
                  "start_point": [80, 20],
                  "end_point": [20, 20]
                },
                {
                  "curve_id": "line_4",
                  "type": "line",
                  "start_point": [20, 20],
                  "end_point": [20, 60]
                },
                {
                  "curve_id": "line_5",
                  "type": "line",
                  "start_point": [20, 60],
                  "end_point": [0, 60]
                },
                {
                  "curve_id": "line_6",
                  "type": "line",
                  "start_point": [0, 60],
                  "end_point": [0, 0]
                }
              ]
            }
          ]
        }
      },
      "operations": [
        {
          "operation_id": "extrude_1",
          "type": "extrude",
          "profile_id": "Profile1",
          "distance": 10,
          "direction": [0, 0, 1],
          "operation_type": "NewBodyFeatureOperation"
        }
      ],
      "features": [
        {
          "feature_id": "fillet_1",
          "type": "fillet",
          "radius": 3.0,
          "edge_selector": "inner_corner",
          "_comment": "Fillet on inner corner of L-bracket"
        }
      ]
    }
  },
  "_description": "L-shaped mounting bracket 80×60×10mm with 20mm thickness and 3mm fillet",
  "_template_category": "mechanical",
  "_editable_parameters": ["base_length", "vertical_length", "thickness", "depth", "fillet_radius"],
  "_engineering_note": "Suitable for 90-degree mounting applications"
}
